#!/usr/bin/python

import paho.mqtt.publish as publish
import socket
import binascii
import time
import sys

###########################
# Variables

listen_address = "0.0.0.0"     # What address to listen to (0.0.0.0 means it will listen on all addresses)
listen_port = 9999             # Port to listen on
client_id = "ginlong"          # MQTT Client ID
mqtt_server = "localhost"      # MQTT Address
mqtt_port = 1833               # MQTT Port

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.bind(listen_address, listen_port)
sock.listen(1)

while True: 
    # Wait for a connection
    print >>sys.stderr, 'waiting for a connection'
    conn,addr = sock.accept()
    try:
        print >>sys.stderr, 'connection from', addr
        while True:
            rawdata = conn.recv(1000)                              # Read in a chunk of data
            print >>sys.stderr, 'received data', rawdata
            hexdata = binascii.hexlify(rawdata)                    # Convert to hex for easier processing
            print >>sys.stderr, 'Hex data: ', hexdata

            if(len(hexdata) != 270):
                msgs = []
                serial = binascii.unhexlify(str(hexdata[42:62]))   # Serial number is used for MQTT path, allowing multiple inverters to connect to a single instance
                print "Serial %s" % serial
                mqtt_topic.join[client_id, "/", serial, "/"]


                msgs.append((mqtt_topic + "test", "test", 0, False))
             
                publish.multiple(msgs hostname=mqtt_server, port=mqtt_port, client_id=client_id)

    finally:
        conn.close()

